### PR TITLE
tidy pristine-zed-garden

### PR DESCRIPTION
**Pull request by Emilene92**
Fixed indentation

### CODE REVIEW

**Comment by marcus-crane** [comment]
You're super close but before I close it, I think it'd be worth it if you had a second pass over the code

For example,

```
  <body id="css-zen-garden">
    <div class="page-wrapper">

     <section class="intro" id="zen-intro">

  <header role="banner">
    <h1>CSS Zen Garden</h1>
    <h2>The Beauty of <abbr title="Cascading Style Sheets">CSS</abbr> Design</h2>
  </header>
```

The code would still work but if it were passed on to someone else, it could get a bit confusing. Does the header fall under the section category? Is the header on the same level as the body in terms of importance?

```
<body id="css-zen-garden">
   <div class="page-wrapper">
      <section class="intro" id="zen-intro"> 
         <header role="banner">
            <h1>CSS Zen Garden</h1>
            <h2>The Beauty of <abbr title="Cascading Style Sheets">CSS</abbr> Design</h2>
         </header>
      </section>
   </div>
</body>
```

If everything is intended towards the right, it's easier to see how elements are ranked and how the page flows. It's also easier to see where divs start and end because when you get a lot of them and you're not sure where the start and end of each one is, it gets very confusing!

Just let me know once you've done any updates and I'll have another look over them. Keep up the good work!

**Comment by Emilene92** [comment]
Hi Marcus, thanks for that. Is it looking better?
@marcus-crane

**Comment by marcus-crane** [comment]
Yup! The last thing is just to watch out for the page-wrapper div. It wraps around the entire page everything below it should be indented. The remaining divs, footer and aside just need to be pushed back to the same level as the <section> tag.

Everything between the start and end of aside should also be indented by one level but they're two minor fixes. Once that's done, you should be sweet!

**Comment by Emilene92** [comment]
Thanks, I think I've done that?
@marcus-crane

**Comment by marcus-crane** [comment]
Yup, spot on! Nice work

**Pull request merged**
